baseurl = "https://info.nvdo.dev"
title = "Home"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-151585915-1"

[params]
    author = "Nguyen Viet Do"
    info = "Most of the time Developer, sometimes Designer :)"
    description = "This is me"
    keywords = "creator,developer,personal"
    avatarurl = "images/author.jpg"

    footercontent = "Nothing down here..."

    hidecredits = true
    hidecopyright = true

    rtl = false

    # math = true
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/vietd24/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/nguyen-viet-do-0b4152163/"

[[params.social]]
    name = "Xing"
    icon = "fab fa-xing fa-2x"
    weight = 3
    url = "https://www.xing.com/profile/NguyenViet_Do/"

# Menu links
[[menu.main]]
    name = "Contact"
    weight = 1
    url = "contact/"
