version: '3'
services:
  hugo:
    image: jguyomard/hugo-builder
    volumes: 
      - ./:/src
    network_mode: "none"
    command: hugo
  nginx:
    build: ./nginx/
    ports:
      - "8888:80"
    volumes:
      - ./public:/public
    depends_on:
      - hugo
    restart: unless-stopped
    